server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/DB_Project
    username: db_project # 본인 username으로 변경해야 함
    password: aAbBcC1! # 해당 username의 password로 변경할 것
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update # 최초 프로젝트 시작시 create(스키마 create) -> 이후부터는 update로 변경하고 실행해야 이전 db 안 날아감
    show-sql: true
    open-in-view: false
  thymeleaf:
    cache: false
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

jwt:
  secret: c29vbmdzaWxfaGVhbHRoX2Fzc29jaWF0aW9u
  accessExpiration: 600000 # 1시간
  refreshExpiration: 604800000 # 7일
