server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/DB_Project
    username: db_project # 본인 username으로 변경해야 함
    password: aAbBcC1! # 해당 username의 password로 변경할 것
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    cache: false