server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/DB_Project
    username: db_project # 본인 username으로 변경해야 함
    password: aAbBcC1! # 해당 username의 password로 변경할 것
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create # 최초 프로젝트 시작시 create(스키마 create) -> 이후부터는 update로 변경하고 실행해야 이전 db 안 날아감
    show-sql: false
  thymeleaf:
    cache: false